-- =============================================
-- 武将槽位基础属性表 (基于 APK 数据反推)
-- 属性体系: genAtt(攻击) genDef(防御) genFor(武力) genLeader(统帅)
-- 成长公式: attr = base + growth × (level - 1)
-- =============================================

CREATE TABLE IF NOT EXISTS `general_slot` (
  `id` INT AUTO_INCREMENT,
  `quality_code` VARCHAR(16) NOT NULL COMMENT '品质: orange/purple/red/blue/green/white',
  `troop_type` VARCHAR(8) NOT NULL COMMENT '兵种: 步/骑/弓',
  `type` VARCHAR(16) NOT NULL COMMENT '类型: 统帅/猛将/智将',
  `slot_index` INT DEFAULT 0 COMMENT '品质内序号',
  `base_attack` INT DEFAULT 0 COMMENT '基础攻击(genAtt)',
  `base_defense` INT DEFAULT 0 COMMENT '基础防御(genDef)',
  `base_valor` INT DEFAULT 0 COMMENT '基础武力(genFor)',
  `base_command` INT DEFAULT 0 COMMENT '基础统帅(genLeader)',
  `base_dodge` DOUBLE DEFAULT 0 COMMENT '基础闪避',
  `base_mobility` INT DEFAULT 0 COMMENT '基础速度',
  `base_power` INT DEFAULT 0 COMMENT '基础战力',
  `growth_attack` DOUBLE DEFAULT 0 COMMENT '攻击成长/级(genAttGrow)',
  `growth_defense` DOUBLE DEFAULT 0 COMMENT '防御成长/级(genDefGrow)',
  `growth_valor` DOUBLE DEFAULT 0 COMMENT '武力成长/级',
  `growth_command` DOUBLE DEFAULT 0 COMMENT '统帅成长/级',
  `base_tactics_trigger_bonus` INT DEFAULT 0 COMMENT '兵法发动概率基础加成(%)',
  `sort_order` INT DEFAULT 0,
  `is_virtual` TINYINT(1) DEFAULT 0 COMMENT '是否虚构武将',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='武将槽位基础属性(APK数据反推)';

-- 清空旧数据后重建
DELETE FROM `general_slot`;

INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (1, 'orange', '步', '统帅', 1, 160, 150, 50, 45, 8, 25, 500, 10.0, 9.0, 3.0, 2.5, 15, 1, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (2, 'orange', '步', '猛将', 2, 175, 130, 55, 35, 5, 22, 480, 11.0, 8.0, 3.5, 2.0, 12, 2, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (3, 'orange', '骑', '猛将', 3, 180, 120, 60, 30, 6, 30, 510, 12.0, 7.5, 4.0, 1.8, 18, 3, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (4, 'orange', '骑', '统帅', 4, 165, 140, 48, 50, 7, 28, 490, 10.5, 8.5, 3.0, 3.0, 15, 4, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (5, 'orange', '弓', '智将', 5, 155, 125, 35, 55, 9, 20, 470, 9.5, 7.5, 2.0, 3.5, 18, 5, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (6, 'orange', '弓', '统帅', 6, 150, 135, 40, 48, 8, 22, 460, 9.0, 8.0, 2.5, 3.0, 15, 6, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (7, 'purple', '步', '统帅', 1, 130, 125, 40, 38, 7, 22, 400, 8.0, 7.5, 2.5, 2.2, 10, 7, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (8, 'purple', '步', '猛将', 2, 140, 115, 45, 30, 5, 20, 380, 8.5, 7.0, 3.0, 1.8, 8, 8, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (9, 'purple', '骑', '统帅', 3, 145, 120, 42, 35, 6, 26, 410, 9.0, 7.0, 2.8, 2.0, 10, 9, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (10, 'purple', '骑', '猛将', 4, 150, 110, 48, 28, 5, 28, 390, 9.5, 6.5, 3.2, 1.6, 8, 10, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (11, 'purple', '弓', '智将', 5, 125, 110, 30, 42, 8, 18, 370, 7.5, 6.5, 1.8, 2.8, 10, 11, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (12, 'purple', '弓', '统帅', 6, 120, 115, 32, 40, 7, 19, 365, 7.0, 7.0, 2.0, 2.5, 8, 12, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (13, 'red', '步', '统帅', 1, 110, 105, 32, 30, 6, 20, 320, 6.5, 6.0, 2.0, 1.8, 5, 13, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (14, 'red', '步', '猛将', 2, 118, 95, 36, 25, 4, 18, 300, 7.0, 5.5, 2.2, 1.5, 3, 14, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (15, 'red', '骑', '统帅', 3, 120, 100, 34, 28, 5, 24, 330, 7.0, 6.0, 2.2, 1.6, 5, 15, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (16, 'red', '骑', '猛将', 4, 125, 90, 38, 22, 4, 25, 310, 7.5, 5.0, 2.5, 1.3, 3, 16, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (17, 'red', '弓', '智将', 5, 105, 95, 25, 35, 7, 16, 290, 6.0, 5.5, 1.5, 2.2, 5, 17, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (18, 'red', '弓', '统帅', 6, 100, 100, 28, 32, 6, 17, 285, 5.5, 6.0, 1.6, 2.0, 3, 18, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (19, 'blue', '步', '统帅', 1, 80, 78, 22, 22, 5, 18, 240, 4.5, 4.5, 1.5, 1.3, 0, 19, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (20, 'blue', '步', '猛将', 2, 88, 70, 26, 18, 3, 16, 220, 5.0, 4.0, 1.8, 1.0, 0, 20, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (21, 'blue', '骑', '统帅', 3, 85, 75, 24, 20, 4, 22, 250, 5.0, 4.0, 1.6, 1.2, 0, 21, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (22, 'blue', '骑', '猛将', 4, 92, 68, 28, 16, 3, 24, 230, 5.5, 3.5, 2.0, 0.9, 0, 22, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (23, 'blue', '弓', '智将', 5, 75, 72, 18, 25, 6, 14, 210, 4.0, 4.0, 1.2, 1.6, 0, 23, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (24, 'blue', '弓', '统帅', 6, 72, 75, 20, 24, 5, 15, 205, 3.8, 4.2, 1.3, 1.5, 0, 24, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (25, 'green', '步', '统帅', 1, 55, 55, 15, 15, 4, 15, 160, 3.0, 3.0, 1.0, 0.9, 0, 25, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (26, 'green', '步', '猛将', 2, 60, 48, 18, 12, 2, 14, 145, 3.5, 2.5, 1.2, 0.7, 0, 26, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (27, 'green', '骑', '统帅', 3, 58, 52, 16, 14, 3, 20, 155, 3.2, 2.8, 1.1, 0.8, 0, 27, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (28, 'green', '骑', '猛将', 4, 65, 45, 20, 10, 2, 22, 140, 3.8, 2.2, 1.3, 0.6, 0, 28, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (29, 'green', '弓', '智将', 5, 50, 50, 12, 18, 5, 12, 135, 2.5, 2.8, 0.8, 1.2, 0, 29, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (30, 'green', '弓', '统帅', 6, 48, 52, 14, 16, 4, 13, 130, 2.3, 3.0, 0.9, 1.0, 0, 30, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (31, 'white', '步', '统帅', 1, 38, 38, 10, 10, 3, 12, 100, 2.0, 2.0, 0.6, 0.6, 0, 31, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (32, 'white', '步', '猛将', 2, 42, 32, 12, 8, 1, 11, 90, 2.3, 1.5, 0.8, 0.5, 0, 32, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (33, 'white', '骑', '统帅', 3, 40, 35, 11, 9, 2, 16, 95, 2.2, 1.8, 0.7, 0.5, 0, 33, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (34, 'white', '骑', '猛将', 4, 45, 30, 14, 7, 1, 18, 85, 2.5, 1.3, 0.9, 0.4, 0, 34, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (35, 'white', '弓', '智将', 5, 35, 35, 8, 12, 4, 10, 80, 1.8, 1.8, 0.5, 0.8, 0, 35, 0);
INSERT INTO `general_slot` (`id`, `quality_code`, `troop_type`, `type`, `slot_index`, `base_attack`, `base_defense`, `base_valor`, `base_command`, `base_dodge`, `base_mobility`, `base_power`, `growth_attack`, `growth_defense`, `growth_valor`, `growth_command`, `base_tactics_trigger_bonus`, `sort_order`, `is_virtual`) VALUES (36, 'white', '弓', '统帅', 6, 33, 37, 9, 11, 3, 11, 78, 1.6, 2.0, 0.6, 0.7, 0, 36, 0);

-- =============================================
-- Lv99 极限属性预览 (公式: base + growth × 98)
-- 橙色步统帅(赵云): genAtt=160+10×98=1140, genDef=150+9×98=1032
-- 橙色骑猛将(吕布): genAtt=180+12×98=1356, genDef=120+7.5×98=855
-- 紫色骑统帅(关羽): genAtt=145+9×98=1027, genDef=120+7×98=806
-- 蓝色步统帅:       genAtt=80+4.5×98=521,  genDef=78+4.5×98=519
-- 绿色步统帅:       genAtt=55+3×98=349,    genDef=55+3×98=349
-- 白色步统帅:       genAtt=38+2×98=234,    genDef=38+2×98=234
-- =============================================